backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

slug:
  encoding: "ascii"
  clean_accents: true

locale: 'cs'

  # These lines should *not* be indented
media_folder: "/static/assets/media" # Media files will be stored in the repo under static/assets/media
public_folder: "/assets/media" # The src attribute for uploaded media will begin with /assets/media

collections:
  - name: "novinky" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Novinky" # Used in the UI, ie.: "New Post"
    create: true
    folder: "content/novinky"
    sortable_fields: ['weight', 'title']
    view_groups:
      - {label: Koncepty, field: draft}
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Alias", name: "linktitle", widget: "string"}
      - {label: "Koncept", name: "draft", widget: "boolean", default: true}
      - {label: "Obrázek", name: "obrazek", widget: "image", required: false}
      - {label: "Soubory", name: "soubory", widget: "file", required: false, media_folder: "/static/assets/media-o-nas", public_folder: "/assets/media-o-nas"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 10000, valueType: int, min: 1, max: 2000000000}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "kempy" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kempy" # Used in the UI, ie.: "New Post"
    create: true
    folder: "content/kempy"
    sortable_fields: ['weight', 'title']
    view_groups:
      - {label: Koncepty, field: draft}
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Alias", name: "linktitle", widget: "string"}
      - {label: "Koncept", name: "draft", widget: "boolean", default: true}
      - {label: "Obrázek", name: "obrazek", widget: "image", required: false}
      - {label: "Soubory", name: "soubory", widget: "file", required: false, media_folder: "/static/assets/media-o-nas", public_folder: "/assets/media-o-nas"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 10000, valueType: int, min: 1, max: 2000000000}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "ostatni" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Ostatní" # Used in the UI, ie.: "New Post"
    create: true
    folder: "content/ostatni"
    sortable_fields: ['weight', 'title']
    view_groups:
      - {label: Koncepty, field: draft}
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Alias", name: "linktitle", widget: "string"}
      - {label: "Koncept", name: "draft", widget: "boolean", default: true}
      - {label: "Obrázek", name: "obrazek", widget: "image", required: false}
      - {label: "Soubory", name: "soubory", widget: "file", required: false, media_folder: "/static/assets/media-o-nas", public_folder: "/assets/media-o-nas"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 10000, valueType: int, min: 1, max: 2000000000}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "o-nas" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "O nás" # Used in the UI, ie.: "New Post"
    create: true
    folder: "content/o-nas"
    media_folder: "/static/assets/media-o-nas"
    public_folder: "/assets/media-o-nas"
    sortable_fields: ['weight', 'title']
    view_groups:
      - {label: Koncepty, field: draft}
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Alias", name: "linktitle", widget: "string"}
      - {label: "Koncept", name: "draft", widget: "boolean", default: true}
      - {label: "Obrázek", name: "obrazek", widget: "image", required: false, media_folder: "/static/assets/media-o-nas", public_folder: "/assets/media-o-nas"}
      - {label: "Soubory", name: "soubory", widget: "file", required: false, media_folder: "/static/assets/media-o-nas", public_folder: "/assets/media-o-nas"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 10000, valueType: int, min: 1, max: 2000000000}
      - {label: "Text", name: "body", widget: "markdown"}
